version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: lptrw-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx:1.23.0-alpine
    container_name: lptrw-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    container_name: lptrw-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql
